### PR TITLE
Fix link to Mastodon's documentation

### PR DESCRIPTION
**Pull request by Hofer-Julian**

### CODE REVIEW

**Comment by klausi** [comment]
https://docs.joinmastodon.org/api/ is an ugly, almost empty page and not really helpful. Maybe better use https://docs.joinmastodon.org/client/intro/ ?

**Comment by Hofer-Julian** [comment]
@klausi done

**Comment by klausi** [comment]
thanks, looks good to me!

**Comment by pwoolcoc** [comment]
the failed builds don't look to be related to this, so I'm just gonna merge it. Thanks for the PR!

**Pull request merged**
