### PR TITLE
feat(media): Add support for media alt text

### LINKED ISSUE #135: Implement media alt text descriptions
Mastodon supports media alt text descriptions for better accessibility. elefren does not support it yet.

I already did this for Mammut in https://github.com/XAMPPRocky/Mammut/pull/46 . Now we need to do this again here because Mammut is unsupported.

### PR DESCRIPTION
**Pull request by klausi**
Fixes #135 .

I have not looked into automated tests yet.

### CODE REVIEW

**Comment by klausi** [comment]
Currently trying to port mastodon-twitter-sync at https://github.com/klausi/mastodon-twitter-sync/compare/elefren-switch

Now the new media() method cannot be found:
```
error[E0599]: no method named `media` found for reference `&elefren::Mastodon` in the current scope
  --> src/post.rs:40:30
   |
40 |             None => mastodon.media(path.into())?,
   |                              ^^^^^ method not found in `&elefren::Mastodon`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use elefren::mastodon_client::MastodonClient;`
```

How can I make the media method public so that it can be used by external applications?

**Comment by klausi** [comment]
Solved this error with `use elefren::MastodonClient;` which I did not see in the examples nor in the docs.

**Comment by pwoolcoc** [comment]
@klausi yea, that gets imported as part of `use elefren::prelude::*` so it isn't too obvious

**Comment by pwoolcoc** [comment]
thanks!

**Pull request merged**
