### PR TITLE
Use std::convert::TryInto

### PR DESCRIPTION
**Pull request by ranfdev**

### CODE REVIEW

**Comment by ranfdev** [comment]
I've rebased so that this change is independent. Now it should be ready to be merged

**Comment by pwoolcoc** [comment]
@ranfdev looks like there are still some conflicts

**Comment by ranfdev** [comment]
Merging #142 inevitably brought up some conflicts. Anyway, now they are fixed

**Comment by pwoolcoc** [comment]
thanks!

**Pull request merged**
